"""Deterministic instruction composition."""

from __future__ import annotations

from agent_bootstrap.agent import Agent, display_target
from agent_bootstrap.config import Manifest, ManifestError

GENERATED_MARKER = "Generated by agent-bootstrap. Do not edit directly."


def render_instructions(manifest: Manifest, host: str, agent: Agent) -> str:
    """Render global instructions for one configured host and agent."""
    fragments = manifest.fragments_for(host, agent)
    source_names = [manifest.display_path(fragment) for fragment in fragments]
    header_lines = [
        "<!--",
        GENERATED_MARKER,
        "",
        f"Host: {host}",
        f"Agent: {agent.value}",
        f"Target: {display_target(agent)}",
        "Sources:",
        *(f"- {name}" for name in source_names),
        "-->",
    ]

    sections = []
    if agent is Agent.CURSOR:
        sections.append("---\nalwaysApply: true\n---")
    sections.append("\n".join(header_lines))
    for fragment, source_name in zip(fragments, source_names, strict=True):
        try:
            content = fragment.read_text(encoding="utf-8")
        except UnicodeDecodeError as error:
            raise ManifestError(f"fragment is not valid UTF-8: {source_name}") from error
        normalized = content.replace("\r\n", "\n").replace("\r", "\n").strip("\n")
        if not normalized.strip():
            raise ManifestError(f"fragment is empty: {source_name}")
        sections.append(normalized)

    return "\n\n".join(sections) + "\n"
