"""Typer CLI integration tests."""

from __future__ import annotations

from pathlib import Path

from typer.testing import CliRunner

from agent_bootstrap.cli import app

runner = CliRunner()


def _manifest(tmp_path: Path) -> Path:
    config = tmp_path / "config"
    config.mkdir()
    (config / "shared.md").write_text("# Shared\n", encoding="utf-8")
    (config / "codex.md").write_text("# Codex\n", encoding="utf-8")
    (config / "pi.md").write_text("# Pi\n", encoding="utf-8")
    (config / "host.md").write_text("# Host\n", encoding="utf-8")
    manifest = config / "manifest.toml"
    manifest.write_text(
        """
schema_version = 2
fragments = ["shared.md"]

[agents.codex]
fragments = ["codex.md"]

[agents.pi]
fragments = ["pi.md"]

[hosts.workstation]
fragments = ["host.md"]
""",
        encoding="utf-8",
    )
    return manifest


def test_render_prints_generated_instructions(tmp_path: Path) -> None:
    manifest = _manifest(tmp_path)

    result = runner.invoke(
        app,
        ["render", "--manifest", str(manifest), "--host", "workstation", "--agent", "codex"],
    )

    assert result.exit_code == 0
    assert "Generated by agent-bootstrap" in result.output
    assert "Agent: codex" in result.output
    assert "# Shared\n\n# Codex\n\n# Host\n" in result.output


def test_dry_run_reports_pi_target_without_writing(tmp_path: Path, monkeypatch: object) -> None:
    manifest = _manifest(tmp_path)
    home = tmp_path / "home"
    home.mkdir()
    monkeypatch.setenv("HOME", str(home))  # type: ignore[attr-defined]

    result = runner.invoke(
        app,
        [
            "install",
            "--manifest",
            str(manifest),
            "--host",
            "workstation",
            "--agent",
            "pi",
            "--dry-run",
            "--diff",
        ],
    )

    assert result.exit_code == 0
    assert f"Target: {home / '.pi/agent/AGENTS.md'}" in result.output
    assert "+# Pi" in result.output
    assert "Would update" in result.output
    assert not (home / ".pi/agent/AGENTS.md").exists()


def test_install_and_check_use_selected_agent_target(tmp_path: Path, monkeypatch: object) -> None:
    manifest = _manifest(tmp_path)
    home = tmp_path / "home"
    home.mkdir()
    monkeypatch.setenv("HOME", str(home))  # type: ignore[attr-defined]

    install_result = runner.invoke(
        app,
        ["install", "--manifest", str(manifest), "--host", "workstation", "--agent", "pi"],
    )
    check_result = runner.invoke(
        app,
        ["check", "--manifest", str(manifest), "--host", "workstation", "--agent", "pi"],
    )

    assert install_result.exit_code == 0
    assert check_result.exit_code == 0
    assert f"Target: {home / '.pi/agent/AGENTS.md'}" in install_result.output
    target = home / ".pi/agent/AGENTS.md"
    assert target.is_file()
    assert "Agent: pi" in target.read_text(encoding="utf-8")
    assert "# Pi" in target.read_text(encoding="utf-8")


def test_check_reports_stale_target(tmp_path: Path, monkeypatch: object) -> None:
    manifest = _manifest(tmp_path)
    home = tmp_path / "home"
    home.mkdir()
    monkeypatch.setenv("HOME", str(home))  # type: ignore[attr-defined]

    result = runner.invoke(
        app,
        ["check", "--manifest", str(manifest), "--host", "workstation", "--agent", "codex"],
    )

    assert result.exit_code == 1
    assert "Stale or missing" in result.output


def test_unknown_host_is_configuration_error(tmp_path: Path) -> None:
    manifest = _manifest(tmp_path)

    result = runner.invoke(
        app,
        ["render", "--manifest", str(manifest), "--host", "laptop", "--agent", "codex"],
    )

    assert result.exit_code == 2
    assert "unknown host 'laptop'" in result.output


def test_agent_option_is_required_and_restricted(tmp_path: Path) -> None:
    manifest = _manifest(tmp_path)

    missing = runner.invoke(app, ["render", "--manifest", str(manifest), "--host", "workstation"])
    invalid = runner.invoke(
        app,
        ["render", "--manifest", str(manifest), "--host", "workstation", "--agent", "claude"],
    )

    assert missing.exit_code == 2
    assert "Missing option '--agent'" in missing.output
    assert invalid.exit_code == 2
    assert "Invalid value for '--agent'" in invalid.output
