"""Typer CLI integration tests."""

from __future__ import annotations

from pathlib import Path

from typer.testing import CliRunner

from agent_bootstrap.cli import app

runner = CliRunner()


def _manifest(tmp_path: Path) -> Path:
    config = tmp_path / "config"
    config.mkdir()
    (config / "shared.md").write_text("# Shared\n", encoding="utf-8")
    (config / "host.md").write_text("# Host\n", encoding="utf-8")
    manifest = config / "manifest.toml"
    manifest.write_text(
        """
schema_version = 1
fragments = ["shared.md"]

[hosts.workstation]
fragments = ["host.md"]
""",
        encoding="utf-8",
    )
    return manifest


def test_render_prints_generated_instructions(tmp_path: Path) -> None:
    manifest = _manifest(tmp_path)

    result = runner.invoke(
        app,
        ["render", "--manifest", str(manifest), "--host", "workstation"],
    )

    assert result.exit_code == 0
    assert "Generated by agent-bootstrap" in result.output
    assert "# Shared\n\n# Host\n" in result.output


def test_install_and_check_use_global_codex_target(tmp_path: Path, monkeypatch: object) -> None:
    manifest = _manifest(tmp_path)
    home = tmp_path / "home"
    home.mkdir()
    monkeypatch.setenv("HOME", str(home))  # type: ignore[attr-defined]

    install_result = runner.invoke(
        app,
        ["install", "--manifest", str(manifest), "--host", "workstation"],
    )
    check_result = runner.invoke(
        app,
        ["check", "--manifest", str(manifest), "--host", "workstation"],
    )

    assert install_result.exit_code == 0
    assert check_result.exit_code == 0
    assert (home / ".codex/AGENTS.md").is_file()


def test_check_reports_stale_target(tmp_path: Path, monkeypatch: object) -> None:
    manifest = _manifest(tmp_path)
    home = tmp_path / "home"
    home.mkdir()
    monkeypatch.setenv("HOME", str(home))  # type: ignore[attr-defined]

    result = runner.invoke(
        app,
        ["check", "--manifest", str(manifest), "--host", "workstation"],
    )

    assert result.exit_code == 1
    assert "Stale or missing" in result.output


def test_unknown_host_is_configuration_error(tmp_path: Path) -> None:
    manifest = _manifest(tmp_path)

    result = runner.invoke(
        app,
        ["render", "--manifest", str(manifest), "--host", "laptop"],
    )

    assert result.exit_code == 2
    assert "unknown host 'laptop'" in result.output
