"""Instruction rendering tests."""

from __future__ import annotations

from pathlib import Path

import pytest

from agent_bootstrap.agent import Agent
from agent_bootstrap.config import ManifestError, load_manifest
from agent_bootstrap.render import GENERATED_MARKER, render_instructions


def _manifest(tmp_path: Path, shared: str = "# Shared\r\n\r\nText\r\n") -> Path:
    (tmp_path / "shared.md").write_bytes(shared.encode())
    (tmp_path / "agent.md").write_text("# Agent\n\nSetting\n\n", encoding="utf-8")
    (tmp_path / "host.md").write_text("# Host\n\nSetting\n\n", encoding="utf-8")
    path = tmp_path / "manifest.toml"
    path.write_text(
        """
schema_version = 2
fragments = ["shared.md"]

[agents.codex]
fragments = ["agent.md"]

[hosts.workstation]
fragments = ["host.md"]
""",
        encoding="utf-8",
    )
    return path


def _schema_v3_manifest(tmp_path: Path) -> Path:
    (tmp_path / "shared.md").write_text("# Shared\n", encoding="utf-8")
    (tmp_path / "codex.md").write_text("# Codex\n", encoding="utf-8")
    (tmp_path / "pi.md").write_text("# Pi\n", encoding="utf-8")
    (tmp_path / "host.md").write_text("# Host\n", encoding="utf-8")
    (tmp_path / "host-codex.md").write_text("# Host Codex\n", encoding="utf-8")
    path = tmp_path / "manifest.toml"
    path.write_text(
        """
schema_version = 3
fragments = ["shared.md"]

[agents.codex]
fragments = ["codex.md"]

[agents.pi]
fragments = ["pi.md"]

[hosts.workstation]
fragments = ["host.md"]

[host_agents.workstation.codex]
fragments = ["host-codex.md"]
""",
        encoding="utf-8",
    )
    return path


def test_render_is_deterministic_and_normalizes_newlines(tmp_path: Path) -> None:
    manifest = load_manifest(_manifest(tmp_path))

    first = render_instructions(manifest, "workstation", Agent.CODEX)
    second = render_instructions(manifest, "workstation", Agent.CODEX)

    assert first == second
    assert GENERATED_MARKER in first
    assert "Host: workstation" in first
    assert "Agent: codex" in first
    assert "Target: ~/.codex/AGENTS.md" in first
    assert "- shared.md\n- agent.md\n- host.md" in first
    assert "\r" not in first
    assert first.endswith("Setting\n")
    assert not first.endswith("\n\n")


def test_schema_v2_rendering_is_byte_identical(tmp_path: Path) -> None:
    manifest = load_manifest(_manifest(tmp_path))

    assert render_instructions(manifest, "workstation", Agent.CODEX) == (
        "<!--\n"
        "Generated by agent-bootstrap. Do not edit directly.\n"
        "\n"
        "Host: workstation\n"
        "Agent: codex\n"
        "Target: ~/.codex/AGENTS.md\n"
        "Sources:\n"
        "- shared.md\n"
        "- agent.md\n"
        "- host.md\n"
        "-->\n"
        "\n"
        "# Shared\n"
        "\n"
        "Text\n"
        "\n"
        "# Agent\n"
        "\n"
        "Setting\n"
        "\n"
        "# Host\n"
        "\n"
        "Setting\n"
    )


@pytest.mark.parametrize(
    ("agent", "target"),
    [
        (Agent.PI, "~/.pi/agent/AGENTS.md"),
        (Agent.ZCODE, "~/.zcode/AGENTS.md"),
        (Agent.CLAUDE, "~/.claude/CLAUDE.md"),
    ],
)
def test_existing_agent_rendering_remains_plain_markdown(
    tmp_path: Path, agent: Agent, target: str
) -> None:
    (tmp_path / "shared.md").write_text("# Shared\n", encoding="utf-8")
    (tmp_path / "agent.md").write_text("# Agent\n", encoding="utf-8")
    (tmp_path / "host.md").write_text("# Host\n", encoding="utf-8")
    path = tmp_path / "manifest.toml"
    path.write_text(
        f"""
schema_version = 2
fragments = ["shared.md"]

[agents.{agent.value}]
fragments = ["agent.md"]

[hosts.workstation]
fragments = ["host.md"]
""",
        encoding="utf-8",
    )

    assert render_instructions(load_manifest(path), "workstation", agent) == (
        "<!--\n"
        "Generated by agent-bootstrap. Do not edit directly.\n"
        "\n"
        "Host: workstation\n"
        f"Agent: {agent.value}\n"
        f"Target: {target}\n"
        "Sources:\n"
        "- shared.md\n"
        "- agent.md\n"
        "- host.md\n"
        "-->\n"
        "\n"
        "# Shared\n"
        "\n"
        "# Agent\n"
        "\n"
        "# Host\n"
    )


def test_cursor_rendering_has_always_apply_frontmatter(tmp_path: Path) -> None:
    (tmp_path / "shared.md").write_text("# Shared\n", encoding="utf-8")
    (tmp_path / "cursor.md").write_text("# Cursor\n", encoding="utf-8")
    (tmp_path / "host.md").write_text("# Host\n", encoding="utf-8")
    path = tmp_path / "manifest.toml"
    path.write_text(
        """
schema_version = 2
fragments = ["shared.md"]

[agents.cursor]
fragments = ["cursor.md"]

[hosts.workstation]
fragments = ["host.md"]
""",
        encoding="utf-8",
    )

    assert render_instructions(load_manifest(path), "workstation", Agent.CURSOR) == (
        "---\n"
        "alwaysApply: true\n"
        "---\n"
        "\n"
        "<!--\n"
        "Generated by agent-bootstrap. Do not edit directly.\n"
        "\n"
        "Host: workstation\n"
        "Agent: cursor\n"
        "Target: ~/.cursor/rules/global.mdc\n"
        "Sources:\n"
        "- shared.md\n"
        "- cursor.md\n"
        "- host.md\n"
        "-->\n"
        "\n"
        "# Shared\n"
        "\n"
        "# Cursor\n"
        "\n"
        "# Host\n"
    )


def test_render_rejects_empty_fragment(tmp_path: Path) -> None:
    manifest = load_manifest(_manifest(tmp_path, shared="\n\n"))

    with pytest.raises(ManifestError, match=r"fragment is empty: shared\.md"):
        render_instructions(manifest, "workstation", Agent.CODEX)


def test_schema_v3_header_includes_only_the_matching_host_agent_fragment(tmp_path: Path) -> None:
    manifest = load_manifest(_schema_v3_manifest(tmp_path))

    codex = render_instructions(manifest, "workstation", Agent.CODEX)
    pi = render_instructions(manifest, "workstation", Agent.PI)

    assert "Sources:\n- shared.md\n- codex.md\n- host.md\n- host-codex.md\n-->" in codex
    assert codex.endswith("# Host\n\n# Host Codex\n")
    assert "Sources:\n- shared.md\n- pi.md\n- host.md\n-->" in pi
    assert "host-codex.md" not in pi


@pytest.mark.parametrize(
    ("content", "message"),
    [(b"\n\n", "fragment is empty: host-codex.md"), (b"\xff", "fragment is not valid UTF-8")],
)
def test_schema_v3_rejects_empty_or_non_utf8_host_agent_fragment(
    tmp_path: Path, content: bytes, message: str
) -> None:
    path = _schema_v3_manifest(tmp_path)
    (tmp_path / "host-codex.md").write_bytes(content)

    with pytest.raises(ManifestError, match=message):
        render_instructions(load_manifest(path), "workstation", Agent.CODEX)
